name: PR Checks

on:
  pull_request:
  workflow_dispatch:

jobs:
  quick-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Quick passthrough
        run: |
          echo "PR quick check passed"
